### ISSUE TITLE
update to sdk 1.9.3

### ISSUE THREAD

**Issue by devoncarew** [daftspaniel/Chocolatey-Packages#1]
Sdk 1.9.3 is out and the current chocolately `dart-sdk` package is 1.8.5. It would be great to have this package rev'd to the latest.

**Comment by DanTup** [comment]
@daftspaniel has taken over maintaining these packages; so this is best raised here:

https://github.com/daftspaniel/Chocolatey-Packages

I'll try and figure out if I can delete this repo and have the url redirect to his!

**Comment by daftspaniel** [comment]
Thanks - will look at updating as soon as I can. Busy few days ahead. Was hoping to get the Dart Editor updated too but no luck contacting the maintainer yet :-/

**Comment by devoncarew** [comment]
@DanTup, I think you can delete this repo, then fork the other one into your account. That'll at least let visitors know there's an upstream repo.

I'll re-file this issue there -

**Comment by devoncarew** [comment]
@daftspaniel, can you enable issues on your repo? Thanks!

**Comment by devoncarew** [comment]
It may be best to try and get the DartEditor one (https://chocolatey.org/packages/DartEditor) removed - it seems hopelessly out of date. Not sure what the process is like for that w/ chocolatey.

**Comment by DanTup** [comment]
@daftspaniel It seems if you delete your fork (which I think only contains the same changesets as this one currently?) I can transfer this one to you; and then any links with my username in will automatically be redirected (and these issues will come with it).

@devoncarew / @daftspaniel Might be worth pinging @ferventcoder about the editor one; if it's badly out of date and not being maintained there might be some process for getting ownership?

**Comment by daftspaniel** [comment]
@DanTup Thanks - I have deleted the fork.

@devoncarew @DanTup - I have tried to get in touch via the Choc site (as their process suggests). I will move it on once I get past my current deadline on Sunday.

**Comment by DanTup** [comment]
@daftspaniel Ok, I've sent the reqest to transfer. Once you click the link in your email, this repo will become yours and URLs with /DanTup/Chocolatey-Packages will all redirect to /daftspaniel/Chocolatey-Packages.

It'll leave me as a contributor, but you're free to remove me from the repo settings page.

**Comment by ferventcoder** [comment]
I can add you as a maintainer of dart editor. I'm not sure if you've tried to reach out to the admins yet, we have quite a large backlog of pkgs and also email related to that. Let me know and I can go look on that

**Comment by daftspaniel** [comment]
@ferventcoder If you could add me as Dart Editor maintainer that would be awesome! :-)

**Comment by daftspaniel** [comment]
I have packed and pushed the updates to Chocolatey. Will close this issue when approved.

**Comment by ferventcoder** [comment]
@daftspaniel done

**Comment by devoncarew** [comment]
closing this -
