### ISSUE TITLE
Update to 1.12.0

### ISSUE THREAD

**Issue by ErikGrimes** [daftspaniel/Chocolatey-Packages#9]
1.12.0 has been released.

**Comment by DanTup** [comment]
1.12.0 has already been submitted to Chocolatey, but in the moderation queue:

https://chocolatey.org/packages/dart-sdk/1.12.0

The queue seems to be quite long/very slow ([info here](https://chocolatey.org/notice)).

**Comment by ErikGrimes** [comment]
Cool and thanks!  I don't see 1.12.0 in this repo. Is there another repo I
should be watching?

**Comment by DanTup** [comment]
Possibly @daftspaniel didn't commit/push when he pushed the update. I'm not involved with this anymore, I just got the notification because I didn't realise I was left "Watching" this repo from when I owned it. I do believe this is still the latest repo!

**Comment by daftspaniel** [comment]
Thanks for point this out @ErikGrimes and thanks for responding @DanTup .

The lag is that I need to fix Git on my Windows Dart machine and then commit. Maybe this weekend depending on other work :-)

Yes 1.12.0 is on chocolatey - just specify at the install 
choco install -y dart-sdk  -version 1.12.0

Cheers!

**Comment by daftspaniel** [comment]
As 1.12.0 and 1.12.1 are added I will close this issue.
